title: Linux
description: A simple blog focused on helping anyone to get Linux certification.
email: 93481036+prying-eye@users.noreply.github.com 
url: https://prying-eye.github.io
github_username: prying-eye
markdown: kramdown
future: true
gems: ['jekyll-gist']
